### PR TITLE
Use shared_ptr to safely close event handles

### LINKED ISSUE #87: VideoCaptureWinRTInternal StopCapture timeout causes the app to crash
`VideoCaptureWinRTInternal::StopCapture` uses a 250 milliseconds timeout when invoking `media_frame_reader_->StopAsync` method. This actually seems to cause a crash whenever the timeout is actually reached, and I guess that this isn't the wanted behavior.

### PR DESCRIPTION
**Pull request by FrayxRulez**
Intends to fix https://github.com/microsoft/winrtc/issues/87
In some (not so) rare cases `SetEvent` gets called after `CloseHandle` causing a `NTSTATUS` (An invalid HANDLE was specified.) error.
Using a `shared_ptr` makes it safe not to manually call ` CloseHandle`.

### CODE REVIEW

File: patches_for_WebRTC_org/m84/src/modules/audio_device/win/audio_device_core_win.h [hunk 1]
```diff
@@ -32,9 +34,10 @@
       goto Cleanup; \
   } while (false)
 
-HRESULT WaitForASyncWithEvent(_In_ IAsyncInfo* async_info,
-                              _In_ HANDLE event_completed_handle,
-                              _In_ DWORD timeout_ms);
+HRESULT WaitForASyncWithEvent(
+    _In_ IAsyncInfo* async_info,
```
Comment (jlautman) [inline patches_for_WebRTC_org/m84/src/modules/audio_device/win/audio_device_core_win.h:38]: Please use the same indentation pattern as the rest of the file.

Comment (FrayxRulez) [reply patches_for_WebRTC_org/m84/src/modules/audio_device/win/audio_device_core_win.h:38]: It should be clang automatic indentation: as `_In_ std::shared_ptr<HANDLE> event_completed_handle_ptr,` is pretty long it already wraps first argument on a new line.
